name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up GitHub CLI
      uses: actions/setup-gh@v0
      with:
          cli-version: 2.x

    - name: Download artifacts
      run: gh run download 7235668123 --workflow "Terraform Workflow"


    - name: Create Variable File
      run: | 
        touch secret.tfvars
        echo aws_access_key = \"${{ secrets.AWS_ACCESS_KEY }}\" >> secret.tfvars
        echo aws_secret_key = \"${{ secrets.AWS_SECRET_KEY }}\" >> secret.tfvars
        echo IP = \"${{ secrets.IP }}\" >> secret.tfvars
        cat secret.tfvars

    - name: Install Terraform
      run: |
        sudo apt-get update && sudo apt-get install -y unzip
        wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
        unzip terraform_0.15.5_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform --version

    - name: Initialize Terraform
      run: |
        terraform init

    - name: Get Run Number
      id: get_run_number
      run: |
        echo "RUN_NUMBER=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | jq -r '.run_number')" >> $GITHUB_ENV
    
    - name: Download Artifacts from Previous Run
      uses: actions/download-artifact@v3
      with:
          name: state-file
          run: 30
          path: ./

    - name: Apply Terraform Configuration
      run: |
        rm terraform.tfstate #delete this finally!!!
        echo "tfstate was removed. Hope this works!" 
        mv artifact/terraform.tfstate .
        terraform apply -auto-approve=true	-var-file="secret.tfvars"
        
    - name: post run check for state file
      run: | 
        ls -l 
        mkdir artifact
        mv terraform.tfstate artifact/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
          name: state-file
          path: artifact/
          retention-days: 30
    


