name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create Variable File
      run: | 
        touch secret.tfvars
        echo aws_access_key = \"${{ secrets.AWS_ACCESS_KEY }}\" >> secret.tfvars
        echo aws_secret_key = \"${{ secrets.AWS_SECRET_KEY }}\" >> secret.tfvars
        echo IP = \"${{ secrets.IP }}\" >> secret.tfvars
        cat secret.tfvars

    - name: Install Terraform
      run: |
        sudo apt-get update && sudo apt-get install -y unzip
        wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
        unzip terraform_0.15.5_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform --version

    - name: Initialize Terraform
      run: |
        terraform init



    - name: Apply Terraform Configuration
      run: |
        terraform apply -auto-approve=true	-var-file="secret.tfvars"
        
    - name: post run check for state file
      run: | 
        ls -l 
        mkdir artifact
        mv terraform.tfstate artifact/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
          name: state-file
          path: artifact/
    
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
          name: my-artifacts
          path: ./

    - name: Apply Terraform Configuration
      run: |
        ls
        cd artifact
        ls 
